### ISSUE TITLE
pain_analysis output is overcounting and should match revised_analysis.

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#10]
Doesn't seem to match the counts outputed by the mturk_revised_analysis sheet.

**Comment by doriensimon** [comment]
Fixed the issue and pushed it the most recent script up to github. The fix was pretty small.

**Comment by mattm401** [comment]
Shouldn't the totals in the pair_analysis also match the output of the revised_analysis?

![image](https://user-images.githubusercontent.com/1121334/80922867-b7d18980-8d34-11ea-84d7-4c393283b737.png)
