### ISSUE TITLE
Updated to dataframe creation script

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#15]
Great job with the first pass on this interface, here are some enhancements:

- [x] Change column header "set" to "Set"
- [x] Change column header "class" to "Multi-class"
- [x] Change column "Input.text" to "Sentence"
- [x] Add filter for is_seed
- [x] Sort final output by "Set" Ascending
- [x] Add filter for top-label classes 
- [x] Add filter for sources
- [x] Add option to specify a source distribution (Random which is what I assume is being done now vs distributed [i.e. take the test set size above and select 20% of the data from each of the selected sources for the test set)
- [x] Add option to set size of test set (default = 20%)
- [x] Add option to specify how many shuffles to do of the data (when randomizing elements)
- [x] Polish interface a bit; add helpful text and position elements in grid grouping like elements together.

**Comment by doriensimon** [comment]
Functions pretty well to my understanding as of now and the UX/UI is ok for the time being I suppose.
