### ISSUE TITLE
Dataframe Manager GUI & Readme Updates

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#16]
Some notes on position (let's left align elements and sort the fields a bit).

![image](https://user-images.githubusercontent.com/1121334/87711374-08fdf080-c75c-11ea-9bc3-ef9af34837f5.png)

Please also take a stab at updating the project README w.r.t to this script and the new scikit-learn script.

I also noticed that is_stressor_confidence doesn't contain an 80%:

![image](https://user-images.githubusercontent.com/1121334/87859205-47281b00-c8e8-11ea-8599-04759e60f1c7.png)

**Comment by doriensimon** [comment]
Can you send me the file that you used to create that iteration of the GUI?

**Comment by mattm401** [comment]
Oh, I didn't make any changes I just full screened the box that popped up.

**Comment by mattm401** [comment]
I also noticed that is_stressor_confidence doesn't contain an 80%
