### ISSUE TITLE
Write settings of Dataframe GUI Tool to text file when creating a dataset

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#17]
...so save along side future experiments.

Add this info as well:
![image](https://user-images.githubusercontent.com/1121334/87719596-73b52900-c768-11ea-897e-04ac0658dec8.png)

**Comment by doriensimon** [comment]
So you want me to return a text file that tells the users which settings they chose to create the dataframe that was returned?

**Comment by mattm401** [comment]
Exactly!

**Comment by doriensimon** [comment]
Got the script outputting a text file that lists all the settings that are INCLUDED in the dataframe. It also includes the dictionary.

**Comment by mattm401** [comment]
Was this not in the latest commit? I am not seeing the output text file for the settings...

**Comment by doriensimon** [comment]
yeah, I forgot to push the recent script. It should be included now
