### ISSUE TITLE
Add Category Upper limit

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#18]
For each category let's allow the user to specify the max number of sentences from each category to use (default = max). This will be tricky when using the distribute datasets option as we want to make sure that we don't too much data from each source.

That being said, let's talk about a concrete example. Work has over 1000 examples, but remember in our projections for scraping the goal was to get all categories pretty close to 555 training examples and so we need to _downsample_ Work.

**Comment by mattm401** [comment]
I see that these are in, great work! Need to add these limits to the setting text file

**Comment by doriensimon** [comment]
Oh yeah, I'll do that

**Comment by doriensimon** [comment]
This is set up to where it will reduce the number of sentences if after filtering the file for the user preferences there are still more sentences than the user limited to. If by chance the filtering of the dataframe reduced the number of labels lower than what was the max the user selected, it will just take the max of labeled sentences in the filtered data frame.
