### ISSUE TITLE
Preliminary Num Turker Analysis

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#19]
- Run dataset aggregation script to generate datasets for turkers 1, 2, 3, 4, 5
- Use data frame script to generate filtered datasets for is_stressor = 1, is_covid = 0
- Run scikit learn script using algorithm = SVC, features = BERT
- Save text output, dataset, dataset settings, and models in a folder
- Aggregate Macro precision, recall, and f1 scores in an excel file
- Generate a graph comparing turker performance using these scores); group P, R, and F1 together for each pool of turks and make it visually easy to look at.

**Comment by mattm401** [comment]
Also compare to original label #20

**Comment by mattm401** [comment]
Example from our conversation today

![image](https://user-images.githubusercontent.com/1121334/88117813-f9721380-cb70-11ea-9eca-470dcc94f43e.png)

**Comment by doriensimon** [comment]
![image](https://user-images.githubusercontent.com/52677013/88236767-99dc3c80-cc32-11ea-8ac6-9960d7fdd4f9.png)
