### ISSUE TITLE
Add original label (text and numeric) from master CSV to...

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#20]
Aggregation Script Output and dataframe GUI output

**Comment by mattm401** [comment]
For Inquire data, we'll have to assign the label in master based on what was used to scrape the data. For inquire_composite let's set that to "Other" for now.

**Comment by doriensimon** [comment]
Can you explain this a little further?

**Comment by mattm401** [comment]
In the MasterCSV for 6/20 (Sent on Slack) there is a field called Answer.label this is the original label that was assigned by the sentence writer (more or less) and we should add this to the output of the aggregation script as "Original Label" and convert it to numerical "Original Multi-class".

The above values in my previous comment is actually done except for inquire_composite which is set to Unknown... let's change these to Other for now.

We may need to think a bit about how this works because the current script distributes based on "Top Label" so we may need to specify that the script for the dataframe GUI should use this Original Label instead of Top Label when we want to compare turkers to the original labeled data.

Let me know if this clears things up...

**Comment by doriensimon** [comment]
So is the aggregation script the script called "mturk_revised_analysis"?

**Comment by mattm401** [comment]
Yes

**Comment by doriensimon** [comment]
Should I convert the Answer.Label to numerical in the "mturk_revised_analysis" script or should I make it numerical in the "filter_file" script?

**Comment by doriensimon** [comment]
And I found all the "Unknown" labels in answer.label. So I convert all the "Unknown" labels under Answer.Label to "Other".

**Comment by mattm401** [comment]
Yea, that seems to make sense to me.

**Comment by doriensimon** [comment]
The mturk_revised_analysis script turns all the 'Uknown' labels to 'Other' and the 'filter_file' script adds another column called 'Original-Multi-Class' which is the labels encoded into numbers using the same encoding for the 'Multi-Class' column that is created by the 'filter_file' script.

**Comment by mattm401** [comment]
I am not seeing the new numeric column on my side, was this not in the recent push?

**Comment by doriensimon** [comment]
I forgot to push the updated script. It should appear now
