### ISSUE TITLE
sci-kit learn output updates

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#22]
Dynamic labeling seems to be a working out well! Two quick tweaks...

- For the data distribution print, let's add the class #s and set the precision of the numerical to 2 decimal places.

- For the confusion matrix, we need to sort the "actual categories" to be ascending... so that the center diagonal should (in theory contain all the times the algorithm gets it right (all the big numbers should be there)

- For the classification report... let's make the labels contain the category (or possibly category + number e.g., "(#) - Work"); if the category name is too long maybe we shorten it by removing the ending characters (replacing them with "...")
![image](https://user-images.githubusercontent.com/1121334/88305167-094b3e00-ccbe-11ea-9910-8b577d3afcfa.png)

![image](https://user-images.githubusercontent.com/1121334/88075881-3b2d9a80-cb2e-11ea-9fa4-77bd99cd06f2.png)

**Comment by doriensimon** [comment]
This is done in recent commit
