### ISSUE TITLE
Add "Original-Multi-class" or this will throw an error

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#23]
in the sci-kit script

![image](https://user-images.githubusercontent.com/1121334/88306497-a9559700-ccbf-11ea-9847-ea8aa1e4d35c.png)

**Comment by doriensimon** [comment]
it throws an error? And would I add it in the if statement?

**Comment by mattm401** [comment]
Yea, just add a check in the if statement. You don't see it on your side?

**Comment by doriensimon** [comment]
I am not thrown an error when I run this

**Comment by mattm401** [comment]
Weird...

![image](https://user-images.githubusercontent.com/1121334/88326287-bc299500-ccda-11ea-859d-4e5ebe4653da.png)

**Comment by doriensimon** [comment]
Nevermind I get the error. Just fixed it and pushed the revised code up.
