### ISSUE TITLE
I recommend copying most (if not all) of console output to the text you're writing with the results

### ISSUE THREAD

**Issue by mattm401** [PervasiveWellbeingTech/Popbots-mTurk-HITS#24]
in the sci-kit script

![image](https://user-images.githubusercontent.com/1121334/88306652-d9049f00-ccbf-11ea-9e66-b82694c8d297.png)

**Comment by doriensimon** [comment]
just about everything is being written to the text file right now I believe.

**Comment by doriensimon** [comment]
error is not thrown on my side....

**Comment by doriensimon** [comment]
woops wrong issue
